defaults: &defaults
  working_directory: /go/src/github.com/hyperledger/burrow
  docker:
    - image: circleci/golang:1.8.1

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - run: go get github.com/Masterminds/glide
      - run: glide install

      # Just persist the entire working dir (burrow checkout)
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test

  test_integration:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: make test_integration

  deploy:
    <<: *defaults
    steps:
      # restore checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 17.06.1-ce
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
      # build docker image and tag the image with the version, date, and commit hash
      - run: tests/build_tool.sh
      - run: docker push quay.io/monax/db


workflows:
  version: 2

  test_and_deploy:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - test_integration:
          requires:
            - checkout_code
      - deploy:
          requires:
            - test
#            - test_integration

